version: "3.2"
services:
  mongo:
    image: mongo:4.4.3
    ports:
    - 27018:27017
    volumes:
    - mongodb:/data/db
  app:
    command: node app.js
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - published: ${APP_PORT:-8000}
        target: 8000
    volumes:
      - .:/app/
    environment:
      JWT_SECRET: ${JWT_SECRET}
volumes:
  mongodb:
